[versions]
managed-rxjava3 = "3.1.12"

micronaut-rxjava2 = "2.9.0"
micronaut = "5.0.0-M22"

rxjava3-bridge = "3.0.2"

[libraries]
# Core
micronaut-core = { module = 'io.micronaut:micronaut-core-bom', version.ref = 'micronaut' }

managed-rxjava3 = { module = "io.reactivex.rxjava3:rxjava", version.ref = "managed-rxjava3" }

micronaut-rxjava2 = { module = "io.micronaut.rxjava2:micronaut-rxjava2-bom", version.ref = "micronaut-rxjava2" }

rxjava3-bridge = { module = "com.github.akarnokd:rxjava3-bridge", version.ref = "rxjava3-bridge" }
rxjava2 = { module = "io.reactivex.rxjava2:rxjava" }
