[versions]
managed-rxjava3-bridge = "3.0.2"
managed-rxjava3 = "3.1.3"

[libraries]
managed-rxjava3-bridge = { module = "com.github.akarnokd:rxjava3-bridge", version.ref = "managed-rxjava3-bridge" }
managed-rxjava3 = { module = "io.reactivex.rxjava3:rxjava", version.ref = "managed-rxjava3" }

# Micronaut
micronaut-graal = { module = "io.micronaut:micronaut-graal" }
micronaut-http-client = { module = "io.micronaut:micronaut-http-client" }
micronaut-http-server-netty = { module = "io.micronaut:micronaut-http-server-netty" }
micronaut-runtime = { module = "io.micronaut:micronaut-runtime" }

rxjava2 = { module = "io.reactivex.rxjava2:rxjava" }
